import express from "express";
import { randomBytes } from "node:crypto";
import { config } from "./config.js";
import { store } from "./store.js";
import { deliver, paymentPayload, redirectUrl } from "./payment.js";
import type { Bill, PaymentMethod } from "./types.js";

const esc=(v:unknown)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
export const app=express(); app.use(express.urlencoded({extended:true})); app.use(express.json());
app.use((req,res,next)=>{ console.log(`${new Date().toISOString()} ${req.method} ${req.path}`); next(); });
function auth(req:express.Request,res:express.Response,next:express.NextFunction){ const token=req.headers.authorization; if(!token?.startsWith("Basic ")) return res.status(401).set("WWW-Authenticate",'Basic realm="Billplz Simulator"').json({error:{message:"Authentication required"}}); const [user]=Buffer.from(token.slice(6),"base64").toString().split(":"); if(user!==config.apiKey)return res.status(401).json({error:{message:"Invalid API key"}}); next(); }
const output=(b:Bill)=>({id:b.id,collection_id:b.collectionId,paid:b.paid,state:b.state,amount:b.amount,paid_amount:b.paidAmount,url:`${config.publicUrl}/bills/${b.id}`,callback_url:b.callbackUrl,redirect_url:b.redirectUrl,description:b.description,email:b.email??null,mobile:b.mobile??null,name:b.name,reference_1:b.reference1??null,reference_2:b.reference2??null});
function create(req:express.Request,res:express.Response){ const p=req.body; const errors:string[]=[]; if(!p.collection_id)errors.push("collection_id is required"); if(!p.name)errors.push("name is required"); if(!Number.isSafeInteger(Number(p.amount))||Number(p.amount)<=0)errors.push("amount must be a positive integer in cents"); for(const k of ["callback_url","redirect_url"])try{new URL(p[k])}catch{errors.push(`${k} must be a valid URL`)} if(errors.length)return res.status(422).json({error:{message:errors}}); const now=new Date().toISOString(); const bill:Bill={id:`sim_${randomBytes(12).toString("hex")}`,collectionId:String(p.collection_id),name:String(p.name),amount:Number(p.amount),paidAmount:0,description:String(p.description||""),callbackUrl:String(p.callback_url),redirectUrl:String(p.redirect_url),paid:false,state:"due",createdAt:now,updatedAt:now,attempts:[]}; for(const [to,from] of [["email","email"],["mobile","mobile"],["reference1Label","reference_1_label"],["reference1","reference_1"],["reference2Label","reference_2_label"],["reference2","reference_2"]] as const)if(p[from])bill[to]=String(p[from]); store.save(bill); res.status(201).json(output(bill)); }
app.post(["/api/v3/bills","/api/bills"],auth,create); app.get(["/api/v3/bills/:id","/api/bills/:id"],auth,(req,res)=>{const b=store.get(String(req.params.id)); return b?res.json(output(b)):res.status(404).json({error:{message:"Bill not found"}})});
app.get("/bills/:id",(req,res)=>{const b=store.get(String(req.params.id)); if(!b)return res.status(404).send("Bill not found"); res.send(`<!doctype html><html><head><meta charset=utf-8><title>Bill ${esc(b.id)}</title><style>body{font:16px system-ui;max-width:900px;margin:40px auto;padding:20px;background:#f6f7fb}section{background:white;padding:20px;margin:16px 0;border-radius:10px}button{padding:10px;margin:5px}.danger{color:#a00}code{word-break:break-all}</style></head><body><h1>Billplz Local Simulator</h1><section><b>${esc(b.description)}</b><p>Bill: <code>${esc(b.id)}</code></p><p>${esc(b.name)} · ${esc(b.email)} · ${esc(b.mobile)}</p><h2>RM ${(b.amount/100).toFixed(2)} — ${esc(b.state)}</h2><small>Callback: ${esc(b.callbackUrl)}<br>Redirect: ${esc(b.redirectUrl)}<br>Attempts: ${b.attempts.length}</small></section><section><h2>Normal scenarios</h2>${[['success_fpx','Successful Online Banking'],['success_card','Successful Credit Card'],['failed','Failed payment'],['cancelled','Cancelled payment'],['callback_only','Callback only'],['redirect_only','Redirect only'],['redirect_first','Redirect before callback'],['duplicate','Duplicate callbacks'],['delayed','Delayed callback']].map(([v,l])=>`<form method=post action=/bills/${b.id}/scenario style="display:inline"><button name=scenario value=${v}>${l}</button></form>`).join('')}</section><section class=danger><h2>Negative tests</h2>${[['invalid_signature','Invalid callback signature'],['modified_amount','Modified amount'],['unknown_id','Unknown bill ID'],['callback_failure','Callback connection failure'],['callback_timeout','Callback timeout'],['invalid_redirect','Invalid redirect signature'],['failed_redirect','Failed redirect'],['server_error','Simulator server error']].map(([v,l])=>`<form method=post action=/bills/${b.id}/scenario style="display:inline"><button name=scenario value=${v}>${l}</button></form>`).join('')}<form method=post action=/bills/${b.id}/scenario><button name=scenario value=resend>Resend most recent callback</button></form></section></body></html>`)});
app.post("/bills/:id/scenario",async(req,res)=>{const b=store.get(String(req.params.id));if(!b)return res.status(404).send("Bill not found");const s=String(req.body.scenario);if(s==="server_error")return res.status(500).send("Simulated server error"); const paid=!['failed','cancelled','failed_redirect'].includes(s); b.paymentMethod=(s==='success_card'?'credit_card':'online_banking') as PaymentMethod;b.scenario=s;b.paid=paid;b.state=paid?'paid':s==='cancelled'?'cancelled':'due';b.paidAmount=paid?b.amount:0; let p=s==='resend'&&b.lastPayload?{...b.lastPayload}:paymentPayload(b,paid);if(s==='invalid_signature')p.x_signature='invalid'+p.x_signature!.slice(7);if(s==='modified_amount'){p.amount=String(b.amount+1);p.x_signature=paymentPayload(b,paid,{amount:p.amount!}).x_signature!}if(s==='unknown_id'){p.id='sim_unknown';p.x_signature=paymentPayload(b,paid,{id:p.id!}).x_signature!} const callback=!['redirect_only','invalid_redirect','failed_redirect'].includes(s); const redirect=!['callback_only','invalid_signature','modified_amount','unknown_id','callback_failure','callback_timeout','resend','delayed','duplicate'].includes(s); if(s==='callback_failure'){const original=b.callbackUrl;b.callbackUrl='http://127.0.0.1:1/unreachable';await deliver(b,p);b.callbackUrl=original}else if(s==='callback_timeout')await deliver(b,p,1);else if(s==='delayed'){setTimeout(()=>void deliver(b,p),2000);return res.send('Callback scheduled in 2 seconds. <a href="/bills/'+b.id+'">Back</a>')}else if(s==='redirect_first'){setTimeout(()=>void deliver(b,p),2000)}else if(callback){await deliver(b,p);if(s==='duplicate')await deliver(b,p)} if(redirect)return res.redirect(303,redirectUrl(b,paid,s==='invalid_redirect'));res.json({bill:output(b),last_attempt:b.attempts.at(-1)});});
app.get("/health",(_req,res)=>res.json({ok:true}));
