'use client'
import { FormEvent,useCallback,useEffect,useState } from 'react'
import { useBranch } from '@/contexts/BranchContext'
import * as api from '@/lib/printPlatform'
import type { PrintDevice,PrintJob } from '@/lib/printPlatform'
type Props={permissions:string[]}
export default function PrintDevicesPage({permissions}:Props){const {selectedBranchId,isAllBranches}=useBranch();const [devices,setDevices]=useState<PrintDevice[]>([]);const [jobs,setJobs]=useState<Record<number,PrintJob[]>>({});const [name,setName]=useState('');const [pairing,setPairing]=useState<{code:string;expires:string}|null>(null);const [notice,setNotice]=useState('');const can=(p:string)=>permissions.includes(p);const canView=can('print.devices.view');const canViewJobs=can('print.jobs.view')
 const load=useCallback(async()=>{if(!canView)return;const r=await api.listPrintDevices(selectedBranchId);setDevices(r.data);if(canViewJobs){const rows=await Promise.all(r.data.map(async d=>[d.id,(await api.listPrintJobs(d.id)).data] as const));setJobs(Object.fromEntries(rows))}},[canView,canViewJobs,selectedBranchId])
 useEffect(()=>{const initial=setTimeout(()=>void load(),0);const timer=setInterval(()=>void load(),15000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load])
 const add=async(e:FormEvent)=>{e.preventDefault();if(!selectedBranchId)return;const r=await api.createPrintDevice(selectedBranchId,name);setPairing({code:r.data.pairing_code,expires:r.data.expires_at});setName('');await load()}
 const action=async(run:()=>Promise<unknown>,message:string)=>{await run();setNotice(message);await load()}
 return <div className="space-y-6">
  {isAllBranches?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">All Branches is a read-only overview. Select a concrete Branch in the Header to pair, revoke, test, or retry.</div>:null}
  {!isAllBranches&&can('print.devices.create')?<form onSubmit={add} className="flex gap-3 rounded-xl border bg-white p-5"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Device name, e.g. GT-POS-01" className="flex-1 rounded-lg border px-3 py-2"/><button className="rounded-lg bg-blue-600 px-4 py-2 text-white">Add / Pair Device</button></form>:null}
  {pairing?<div role="dialog" className="rounded-xl border-2 border-blue-300 bg-blue-50 p-6"><h2 className="font-semibold">One-time Pairing Code</h2><p className="my-3 font-mono text-4xl tracking-widest">{pairing.code}</p><p className="text-sm">Expires {new Date(pairing.expires).toLocaleString()}. This code is displayed only now.</p><button onClick={()=>setPairing(null)} className="mt-3 underline">Close</button></div>:null}{notice?<p className="text-sm text-emerald-700">{notice}</p>:null}
  <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr>{isAllBranches?<th className="p-3">Branch</th>:null}<th className="p-3">Device</th><th className="p-3">Status</th><th className="p-3">Last seen</th><th className="p-3">App</th><th className="p-3">Printers</th><th className="p-3">Actions</th></tr></thead><tbody>{devices.map(d=><tr key={d.id} className="border-t align-top">{isAllBranches?<td className="p-3">{d.store_location.name}</td>:null}<td className="p-3"><b>{d.name}</b><div className="text-xs text-slate-500">{d.uuid}</div></td><td className="p-3">{d.status==='revoked'?'Revoked':d.online?'● Online':'○ Offline'}</td><td className="p-3">{d.last_seen_at?new Date(d.last_seen_at).toLocaleString():'Never'}</td><td className="p-3">{d.app_version||'—'}</td><td className="p-3">{d.printers_count} <span className="text-xs text-slate-500">(Phase 2 setup)</span></td><td className="p-3 space-x-2">{!isAllBranches&&d.status!=='revoked'?<>{can('print.jobs.create-test')?<button className="text-blue-700" onClick={()=>void action(()=>api.testPrint(d.id),'Test print queued.')}>Test Print</button>:null}{can('print.devices.create')?<button className="text-blue-700" onClick={async()=>{const r=await api.regeneratePairingCode(d.id);setPairing({code:r.data.pairing_code,expires:r.data.expires_at})}}>Pairing Code</button>:null}{can('print.devices.revoke')?<button className="text-red-700" onClick={()=>confirm('Revoke this device?')&&void action(()=>api.revokePrintDevice(d.id),'Device revoked.')}>Revoke</button>:null}</>:null}</td></tr>)}{devices.length===0?<tr><td colSpan={7} className="p-8 text-center text-slate-500">No Print Devices found.</td></tr>:null}</tbody></table></div>
  {devices.map(d=><section key={`jobs-${d.id}`} className="rounded-xl border bg-white p-5"><h2 className="font-semibold">{d.name} — Recent Jobs</h2><div className="mt-3 space-y-2">{(jobs[d.id]||[]).slice(0,10).map(j=><div key={j.id} className="flex items-center justify-between border-t py-2"><span><b>{j.type.toUpperCase()}</b> <span className="text-xs text-slate-500">{j.id}</span></span><span>{j.status}{!isAllBranches&&['failed','cancelled'].includes(j.status)&&can('print.jobs.retry')?<button className="ml-3 text-blue-700" onClick={()=>void action(()=>api.retryPrintJob(j.id),'Retry queued.')}>Retry</button>:null}</span></div>)}</div></section>)}
 </div>}
