import test from "node:test";
import assert from "node:assert/strict";
import { createServer } from "node:http";
import { app } from "../src/app.js";
import { config } from "../src/config.js";
import { sign, sourceString } from "../src/signature.js";
import { store } from "../src/store.js";

const auth={authorization:`Basic ${Buffer.from(`${config.apiKey}:`).toString("base64")}`};
async function withServer(run:(base:string)=>Promise<void>){const server=createServer(app);await new Promise<void>(r=>server.listen(0,"127.0.0.1",r));const address=server.address();try{await run(`http://127.0.0.1:${typeof address==='object'&&address?address.port:0}`)}finally{await new Promise<void>((r,j)=>server.close(e=>e?j(e):r()))}}
const body={collection_id:"collection",email:"a@example.test",name:"Test",amount:"1234",description:"Order A",callback_url:"http://127.0.0.1:1/callback",redirect_url:"http://shop.test/payment-result",reference_1:"A"};
test("signature contracts",()=>{assert.equal(sourceString({paid:"true",id:"x"}),"idx|paidtrue");assert.equal(sign({paid:"true",id:"x"},"secret"),"9b1a92a5a2cd6f8f0b78867e6ea414586ed0b4809ade4a35e084c3b03f931adf");assert.match(sourceString({paid:"true",id:"x"},true),/^billplz/)});
test("auth, validation, creation, integer amount, lookup and unknown lookup",()=>withServer(async base=>{store.clear();assert.equal((await fetch(`${base}/api/v3/bills`,{method:"POST"})).status,401);assert.equal((await fetch(`${base}/api/v3/bills`,{method:"POST",headers:{...auth,"content-type":"application/json"},body:"{}"})).status,422);const created=await fetch(`${base}/api/v3/bills`,{method:"POST",headers:{...auth,"content-type":"application/json"},body:JSON.stringify(body)});assert.equal(created.status,201);const bill=await created.json() as {id:string,amount:number};assert.equal(bill.amount,1234);assert.equal((await fetch(`${base}/api/v3/bills/${bill.id}`,{headers:auth})).status,200);assert.equal((await fetch(`${base}/api/v3/bills/nope`,{headers:auth})).status,404)}));
test("online banking, card, invalid signature, changed amount and duplicate callbacks",()=>withServer(async base=>{store.clear();const callback=createServer((req,res)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{assert.match(req.headers['content-type']||'',/application\/x-www-form-urlencoded/);res.end('OK')})});await new Promise<void>(r=>callback.listen(0,"127.0.0.1",r));const a=callback.address();const data={...body,callback_url:`http://127.0.0.1:${typeof a==='object'&&a?a.port:0}`};const created=await fetch(`${base}/api/bills`,{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify(data)});const bill=await created.json() as {id:string};for(const scenario of ['success_fpx','success_card','invalid_signature','modified_amount','duplicate'])await fetch(`${base}/bills/${bill.id}/scenario`,{method:'POST',redirect:'manual',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({scenario})});const stored=store.get(bill.id)!;assert.equal(stored.paymentMethod,'online_banking');assert.equal(stored.attempts.length,6);assert.equal(stored.attempts[0]?.delivered,true);assert.notEqual(stored.attempts[2]?.payload.x_signature,sign(Object.fromEntries(Object.entries(stored.attempts[2]!.payload).filter(([k])=>k!=='x_signature')),config.signatureKey));await new Promise<void>((r,j)=>callback.close(e=>e?j(e):r()))}));
test("redirect query and invalid redirect signature",()=>withServer(async base=>{store.clear();const created=await fetch(`${base}/api/bills`,{method:'POST',headers:{...auth,'content-type':'application/json'},body:JSON.stringify(body)});const bill=await created.json() as {id:string};for(const scenario of ['redirect_only','invalid_redirect']){const response=await fetch(`${base}/bills/${bill.id}/scenario`,{method:'POST',redirect:'manual',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({scenario})});assert.equal(response.status,303);assert.match(response.headers.get('location')||'',/billplz%5Bid%5D=/)}}));
