<?php
namespace App\Http\Controllers;
use App\Models\Expense; use App\Models\ExpenseCategory; use Carbon\Carbon; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Storage; use Illuminate\Validation\Rule;
class ExpenseController extends Controller {
 private function filtered(Request $r) { $q=Expense::query()->with(['category','creator'])->orderByDesc('expense_date')->orderByDesc('id'); if($month=$r->string('month')->toString()){try{$d=Carbon::createFromFormat('Y-m',$month);$q->whereBetween('expense_date',[$d->startOfMonth()->toDateString(),$d->endOfMonth()->toDateString()]);}catch(\Throwable $e){abort(422,'Month must use YYYY-MM format.');}} if($r->filled('expense_category_id'))$q->where('expense_category_id',$r->integer('expense_category_id')); if($search=trim($r->string('search')->toString()))$q->where(fn($x)=>$x->where('expense_no','like',"%$search%")->orWhere('title','like',"%$search%")->orWhere('remark','like',"%$search%")->orWhereHas('category',fn($c)=>$c->where('name','like',"%$search%"))); return $q; }
 public function index(Request $r){$q=$this->filtered($r);$total=(clone $q)->sum('amount');$items=$q->paginate(min(max($r->integer('per_page',15),1),100))->withQueryString();return $this->respond(['items'=>$items,'total_expense'=>(string)$total]);}
 public function show(Expense $expense){return $this->respond($expense->load(['category','creator','updater']));}
 private function rules(?Expense $expense=null): array{return ['expense_category_id'=>['required','integer',Rule::exists('expense_categories','id')->where('is_active',true)],'expense_date'=>'required|date','title'=>'required|string|max:150','amount'=>'required|numeric|gt:0|decimal:0,2','remark'=>'nullable|string','receipt'=>'nullable|file|mimes:jpg,jpeg,png,pdf|max:5120','remove_receipt'=>'nullable|boolean'];}
 private function receipt(Request $r,?Expense $expense): ?string {if($r->hasFile('receipt')){if($expense?->receipt_path)Storage::disk('public')->delete($expense->receipt_path);return $r->file('receipt')->store('expenses/receipts','public');}if($r->boolean('remove_receipt')&&$expense?->receipt_path){Storage::disk('public')->delete($expense->receipt_path);return null;}return $expense?->receipt_path;}
 public function store(Request $r){$v=$r->validate($this->rules());$user=$r->user();$expense=DB::transaction(function()use($r,$v,$user){$date=Carbon::parse($v['expense_date']);$prefix='EXP-'.$date->format('Ym').'-';$last=Expense::withTrashed()->where('expense_no','like',$prefix.'%')->lockForUpdate()->orderByDesc('id')->value('expense_no');$sequence=$last ? ((int)substr($last,-5))+1 : 1;return Expense::create([...$v,'expense_no'=>$prefix.str_pad((string)$sequence,5,'0',STR_PAD_LEFT),'receipt_path'=>$this->receipt($r,null),'created_by'=>$user->id,'updated_by'=>$user->id]);});return $this->respond($expense->load(['category','creator']),'Expense created successfully.');}
 public function update(Request $r,Expense $expense){$v=$r->validate($this->rules($expense));$expense->update([...$v,'receipt_path'=>$this->receipt($r,$expense),'updated_by'=>$r->user()->id]);return $this->respond($expense->fresh(['category','creator','updater']),'Expense updated successfully.');}
 public function destroy(Request $r,Expense $expense){$expense->update(['updated_by'=>$r->user()->id]);$expense->delete();return $this->respond(null,'Expense archived successfully.');}
 public function export(Request $r){$rows=$this->filtered($r)->get();return response()->streamDownload(function()use($rows){$out=fopen('php://output','w');fputcsv($out,['Expense No','Expense Date','Expense Title','Category','Amount','Remark','Created By','Created At']);foreach($rows as $e)fputcsv($out,[$e->expense_no,$e->expense_date->format('Y-m-d'),$e->title,$e->category?->name,$e->amount,$e->remark,$e->creator?->name,$e->created_at]);fputcsv($out,['','','','Total Expense',(string)$rows->sum('amount')]);fclose($out);},'expenses.csv',['Content-Type'=>'text/csv; charset=UTF-8']);}
}
