'use client'

import { ChangeEvent, FormEvent, useState } from 'react'
import type { BookingServiceRowData } from './BookingServiceRow'
import { mapBookingServiceApiItemToRow, type BookingServiceApiItem } from './bookingServiceUtils'

interface BookingServiceCreateModalProps { onClose: () => void; onSuccess: (service: BookingServiceRowData) => void }
interface FormState { name:string; description:string; service_type:'premium'|'standard'; duration_min:string; service_price:string; deposit_amount:string; buffer_min:string; is_active:boolean; imageFile:File|null }
const initial: FormState = { name:'',description:'',service_type:'standard',duration_min:'30',service_price:'0',deposit_amount:'0',buffer_min:'15',is_active:true,imageFile:null }

export default function BookingServiceCreateModal({ onClose, onSuccess }: BookingServiceCreateModalProps) {
  const [form,setForm]=useState<FormState>({...initial}); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState<string|null>(null)
  const handleChange=(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{const {name,value,type}=e.target as HTMLInputElement; setForm((p)=>({...p,[name]:type==='checkbox'?(e.target as HTMLInputElement).checked:value}))}
  const handleSubmit=async(e:FormEvent)=>{e.preventDefault(); setSubmitting(true); setError(null); try{const fd=new FormData(); Object.entries(form).forEach(([k,v])=>{if(k==='imageFile')return; fd.append(k, String(v))}); if(form.imageFile) fd.append('image',form.imageFile); const res=await fetch('/api/proxy/admin/booking/services',{method:'POST',body:fd}); const data=await res.json().catch(()=>null); if(!res.ok){setError((data as {message?:string})?.message ?? 'Failed to create booking service');return;} onSuccess(mapBookingServiceApiItemToRow((data?.data??{}) as BookingServiceApiItem));}catch{setError('Failed to create booking service')}finally{setSubmitting(false)}}
  return <div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/50" onClick={onClose}/><div className="relative w-full max-w-lg bg-white rounded-lg p-5"><h2 className="font-semibold mb-3">Create Booking Service</h2><form onSubmit={handleSubmit} className="space-y-3"><input name="name" value={form.name} onChange={handleChange} className="w-full border p-2 rounded" placeholder="Name"/><select name="service_type" value={form.service_type} onChange={handleChange} className="w-full border p-2 rounded"><option value="standard">Standard</option><option value="premium">Premium</option></select><textarea name="description" value={form.description} onChange={handleChange} className="w-full border p-2 rounded"/><input name="duration_min" value={form.duration_min} onChange={handleChange} className="w-full border p-2 rounded"/><input name="service_price" value={form.service_price} onChange={handleChange} className="w-full border p-2 rounded"/><input name="deposit_amount" value={form.deposit_amount} onChange={handleChange} className="w-full border p-2 rounded"/><input name="buffer_min" value={form.buffer_min} onChange={handleChange} className="w-full border p-2 rounded"/><input type="file" accept="image/*" onChange={(e)=>setForm((p)=>({...p,imageFile:e.target.files?.[0]??null}))}/>{error&&<div className="text-red-600 text-sm">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="border px-3 py-2 rounded">Cancel</button><button disabled={submitting} className="bg-blue-600 text-white px-3 py-2 rounded">Create</button></div></form></div></div>
}
