'use client'

import { ChangeEvent, FormEvent, useEffect, useState } from 'react'
import type { BookingServiceRowData } from './BookingServiceRow'
import { mapBookingServiceApiItemToRow, type BookingServiceApiItem } from './bookingServiceUtils'

interface Props { serviceId:number; onClose:()=>void; onSuccess:(service:BookingServiceRowData)=>void }
interface FormState { name:string; description:string; service_type:'premium'|'standard'; duration_min:string; service_price:string; deposit_amount:string; buffer_min:string; is_active:boolean; imageFile:File|null; imageUrl:string }
const initial: FormState={name:'',description:'',service_type:'standard',duration_min:'30',service_price:'0',deposit_amount:'0',buffer_min:'15',is_active:true,imageFile:null,imageUrl:''}

export default function BookingServiceEditModal({serviceId,onClose,onSuccess}:Props){
 const [form,setForm]=useState<FormState>({...initial}); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false)
 useEffect(()=>{(async()=>{const res=await fetch(`/api/proxy/admin/booking/services/${serviceId}`); const data=await res.json(); const s=data?.data as BookingServiceApiItem; if(s){setForm((p)=>({...p,name:String(s.name??''),description:String(s.description??''),service_type:(s as any).service_type==='premium'?'premium':'standard',duration_min:String(s.duration_min??30),service_price:String(s.service_price??0),deposit_amount:String(s.deposit_amount??0),buffer_min:String(s.buffer_min??15),is_active:Boolean(s.is_active===true||s.is_active===1||s.is_active==='1'||s.is_active==='true'),imageUrl:String((s as any).image_url??(s as any).image_path??'')}))} setLoading(false)})()},[serviceId])
 const handleChange=(e:ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>{const {name,value,type}=e.target as HTMLInputElement; setForm((p)=>({...p,[name]:type==='checkbox'?(e.target as HTMLInputElement).checked:value}))}
 const handleSubmit=async(e:FormEvent)=>{e.preventDefault(); setSubmitting(true); const fd=new FormData(); fd.append('_method','PUT'); ['name','description','service_type','duration_min','service_price','deposit_amount','buffer_min'].forEach((k)=>fd.append(k,String((form as any)[k]))); fd.append('is_active', form.is_active?'1':'0'); if(form.imageFile) fd.append('image', form.imageFile); const res=await fetch(`/api/proxy/admin/booking/services/${serviceId}`,{method:'PUT',body:fd}); const data=await res.json().catch(()=>null); if(res.ok) onSuccess(mapBookingServiceApiItemToRow((data?.data??{}) as BookingServiceApiItem)); setSubmitting(false)}
 if(loading) return null
 return <div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/50" onClick={onClose}/><div className="relative w-full max-w-lg bg-white rounded-lg p-5"><h2 className="font-semibold mb-3">Edit Booking Service</h2><form onSubmit={handleSubmit} className="space-y-3"><input name="name" value={form.name} onChange={handleChange} className="w-full border p-2 rounded"/><select name="service_type" value={form.service_type} onChange={handleChange} className="w-full border p-2 rounded"><option value="standard">Standard</option><option value="premium">Premium</option></select><textarea name="description" value={form.description} onChange={handleChange} className="w-full border p-2 rounded"/>{form.imageUrl && <img src={form.imageUrl} className="h-16 w-16 object-cover rounded" alt="Current"/>}<input type="file" accept="image/*" onChange={(e)=>setForm((p)=>({...p,imageFile:e.target.files?.[0]??null}))}/><button disabled={submitting} className="bg-blue-600 text-white px-3 py-2 rounded">Save</button></form></div></div>
}
