'use client'

import { FormEvent, useCallback, useEffect, useState } from 'react'
import { Switch } from '@/components/ui/switch'

type Option = { label: string; cn_label: string; is_active: boolean; allow_quantity: boolean }
type Preset = { id: number; name: string; title: string; cn_title?: string | null; description?: string | null; cn_description?: string | null; question_type: 'single_choice' | 'multi_choice'; is_required: boolean; is_active: boolean; options_count?: number; options?: Option[] }
const blank = (): Omit<Preset, 'id'> => ({ name: '', title: '', cn_title: '', description: '', cn_description: '', question_type: 'single_choice', is_required: false, is_active: true, options: [{ label: '', cn_label: '', is_active: true, allow_quantity: true }] })

export default function BookingQuestionPresetsPage({ permissions }: { permissions: string[] }) {
  const [rows, setRows] = useState<Preset[]>([]), [search, setSearch] = useState(''), [loading, setLoading] = useState(true)
  const [editing, setEditing] = useState<Preset | null>(null), [form, setForm] = useState<Omit<Preset, 'id'>>(blank()), [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch(`/api/proxy/admin/booking/question-presets?per_page=100&search=${encodeURIComponent(search)}`, { cache: 'no-store' }); const j = await r.json().catch(() => null); setRows(Array.isArray(j?.data?.data) ? j.data.data : []) } finally { setLoading(false) } }, [search])
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer) }, [load])
  const open = async (row?: Preset) => { if (!row) { setEditing(null); setForm(blank()); return } const r = await fetch(`/api/proxy/admin/booking/question-presets/${row.id}`, { cache: 'no-store' }); const j = await r.json(); setEditing(row); setForm({ ...j.data, options: j.data.options.map((o: Option) => ({ label: o.label, cn_label: o.cn_label ?? '', is_active: o.is_active, allow_quantity: o.allow_quantity })) }) }
  const save = async (e: FormEvent) => { e.preventDefault(); setSaving(true); try { const r = await fetch(`/api/proxy/admin/booking/question-presets${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json', Accept: 'application/json' }, body: JSON.stringify(form) }); if (r.ok) { setEditing(null); setForm(blank()); await load() } else alert((await r.json().catch(() => null))?.message ?? 'Unable to save preset') } finally { setSaving(false) } }
  const remove = async (row: Preset) => { if (!confirm(`Delete preset “${row.name}”? Previously copied service questions will not be affected.`)) return; const r = await fetch(`/api/proxy/admin/booking/question-presets/${row.id}`, { method: 'DELETE' }); if (r.ok) load() }
  const showForm = editing !== null || form.name !== '' || form.title !== ''
  return <div className="space-y-5">
    <div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search preset name or question title…" className="w-full max-w-md rounded-lg border px-3 py-2" />{permissions.includes('booking.question-presets.create') && <button onClick={() => { setEditing(null); setForm({ ...blank(), name: ' ' }) }} className="rounded-lg bg-blue-600 px-4 py-2 text-white"><i className="fa-solid fa-plus mr-2" />Create Preset</button>}</div>
    {showForm && <form onSubmit={save} className="rounded-xl border bg-white p-5 shadow-sm space-y-4">
      <div className="flex justify-between"><h3 className="text-lg font-semibold">{editing ? 'Edit' : 'Create'} Question Preset</h3><button type="button" onClick={() => { setEditing(null); setForm(blank()) }}><i className="fa-solid fa-xmark" /></button></div>
      <div className="grid gap-3 md:grid-cols-2">{([['name','Preset Name'],['title','Question Title'],['cn_title','Chinese Question Title'],['description','Description'],['cn_description','Chinese Description']] as const).map(([key,label]) => <label key={key} className={key === 'name' ? 'md:col-span-2' : ''}><span className="mb-1 block text-sm font-medium">{label}</span><input required={key === 'name' || key === 'title'} value={String(form[key] ?? '').trimStart()} onChange={(e) => setForm((p) => ({ ...p, [key]: e.target.value }))} className="w-full rounded border px-3 py-2" /></label>)}</div>
      <select value={form.question_type} onChange={(e) => setForm((p) => ({ ...p, question_type: e.target.value as Preset['question_type'] }))} className="w-full rounded border px-3 py-2"><option value="single_choice">Single choice</option><option value="multi_choice">Multi choice</option></select>
      <div className="grid gap-3 sm:grid-cols-2"><Toggle label="Required" value={form.is_required} onChange={(v) => setForm((p) => ({ ...p, is_required: v }))} /><Toggle label="Status" value={form.is_active} onChange={(v) => setForm((p) => ({ ...p, is_active: v }))} /></div>
      <div className="rounded-lg border bg-gray-50 p-4 space-y-3"><div className="flex justify-between"><div><b>Options</b><p className="text-xs text-gray-500">Add-on services are selected after applying this preset.</p></div><button type="button" onClick={() => setForm((p) => ({ ...p, options: [...(p.options ?? []), { label: '', cn_label: '', is_active: true, allow_quantity: true }] }))} className="rounded border bg-white px-3 py-1 text-sm">Add option</button></div>
        {(form.options ?? []).map((option, i) => <div key={i} className="rounded border bg-white p-3 space-y-2"><div className="flex justify-between"><b className="text-sm">Option #{i+1}</b><div className="space-x-2"><button type="button" disabled={i===0} onClick={() => setForm((p) => ({...p, options: move(p.options ?? [], i, i-1)}))}>↑</button><button type="button" disabled={i===(form.options?.length ?? 0)-1} onClick={() => setForm((p) => ({...p, options: move(p.options ?? [], i, i+1)}))}>↓</button><button type="button" className="text-red-600" onClick={() => setForm((p) => ({...p, options: p.options?.filter((_,x)=>x!==i)}))}>Delete</button></div></div><div className="grid gap-2 md:grid-cols-2"><input required value={option.label} placeholder="Label" onChange={(e)=>setForm((p)=>({...p,options:p.options?.map((o,x)=>x===i?{...o,label:e.target.value}:o)}))} className="rounded border px-3 py-2"/><input value={option.cn_label} placeholder="Chinese label" onChange={(e)=>setForm((p)=>({...p,options:p.options?.map((o,x)=>x===i?{...o,cn_label:e.target.value}:o)}))} className="rounded border px-3 py-2"/></div><div className="grid gap-2 sm:grid-cols-2"><Toggle label="Status" value={option.is_active} onChange={(v)=>setForm((p)=>({...p,options:p.options?.map((o,x)=>x===i?{...o,is_active:v}:o)}))}/><Toggle label="Allow quantity in POS" value={option.allow_quantity} onChange={(v)=>setForm((p)=>({...p,options:p.options?.map((o,x)=>x===i?{...o,allow_quantity:v}:o)}))}/></div></div>)}
      </div><button disabled={saving} className="rounded-lg bg-blue-600 px-5 py-2 text-white disabled:opacity-50">{saving ? 'Saving…' : 'Save Preset'}</button>
    </form>}
    <div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-sm"><thead className="bg-gray-50"><tr><th className="p-3 text-left">Preset Name</th><th className="p-3 text-left">Question</th><th className="p-3">Type</th><th className="p-3">Options</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan={6} className="p-8 text-center">Loading…</td></tr> : rows.map((row)=><tr key={row.id} className="border-t"><td className="p-3 font-medium">{row.name}</td><td className="p-3">{row.title}</td><td className="p-3 text-center">{row.question_type==='multi_choice'?'Multi':'Single'}</td><td className="p-3 text-center">{row.options_count}</td><td className="p-3 text-center">{row.is_active?'Active':'Inactive'}</td><td className="p-3 text-center space-x-3">{permissions.includes('booking.question-presets.update')&&<button onClick={()=>open(row)} className="text-blue-600">Edit</button>}{permissions.includes('booking.question-presets.delete')&&<button onClick={()=>remove(row)} className="text-red-600">Delete</button>}</td></tr>)}</tbody></table></div>
  </div>
}
function Toggle({label,value,onChange}:{label:string,value:boolean,onChange:(v:boolean)=>void}) { return <div className="flex items-center justify-between rounded border bg-white px-3 py-2"><span className="text-sm font-medium">{label}</span><Switch checked={value} onCheckedChange={onChange}/></div> }
function move<T>(rows:T[],from:number,to:number){const copy=[...rows];const [item]=copy.splice(from,1);copy.splice(to,0,item);return copy}
